In [10]:
import tkinter as tk
import sqlite3

root = tk.Tk()
root.geometry('1000x1500')

fullname_var = tk.StringVar()
firstname_var = tk.StringVar()
email_var = tk.StringVar()
education_var = tk.StringVar()
address_var = tk.StringVar()
address1_var = tk.StringVar()
phone = tk.StringVar()

def submit():
    con1 = sqlite3.connect("registeredschool.db")
    cur1 = con1.cursor()

    name = fullname_var.get()
    firstname = firstname_var.get()
    email = email_var.get()
    education = education_var.get()
    address = address_var.get()
    address1 = address1_var.get()
    phone1 = phone.get()

    cur = cur1.execute('CREATE TABLE IF NOT EXISTS STUD (Fullname TEXT,Firstname TEXT,Email TEXT,Education TEXT,Address TEXT,Address1 TEXT,Phone TEXT)')
    cursor = cur1.execute("INSERT INTO STUD (Fullname,Firstname,Email,Education,Address,Address1,Phone) VALUES (?,?,?,?,?,?,?)"
                      ,(name, firstname,email,education,address,address1,phone1))
    cursor1 = cur1.execute("SELECT Fullname,Firstname,Email,Education,Address,Address1,Phone from STUD")
    for row in cursor1:
        print("FULL NAME = ", row[0])
        print("FIRST NAME = ", row[1])
        print("EMAIL = ", row[2])
        print("EDUCATION = ", row[3])
        print("ADDRESS = ", row[4])
        print("ADDRESS 1 = ", row[5])
        print("PHONE = ", row[6], "\n")

    con1.commit()
    con1.close()


    fullname_var.set("")
    firstname_var.set("")
    email_var.set("")
    education_var.set("")
    address_var.set("")
    address1_var.set("")
    phone.set("")
    
    

root.title("Job Application")


label_0 = tk.Label(root, text="Job Application",width=20,fg='black',font=("bold", 20))
label_0.place(x=25,y=0)

label_0 = tk.Label(root, text="Personal Information",width=20,fg='brown',font=("bold", 20))
label_0.place(x=15,y=40)


fullName_1 = tk.Label(root, text="FullName",width=10,font=("bold", 10))
fullName_1.place(x=80,y=90)

entry_fullN = tk.Entry(root,textvariable=fullname_var)
entry_fullN.place(x=220,y=90)

firstname = tk.Label(root, text="First Name",width=15,font=("bold", 8))
firstname.place(x=200,y=110)

firstname_entry = tk.Entry(root,textvariable=firstname_var)
firstname_entry.place(x=350,y=90)

email = tk.Label(root, text="Email",width=20,font=("bold", 10))
email.place(x=50,y=140)

email_entry = tk.Entry(root,width=40,textvariable=email_var)
email_entry.place(x=220,y=140)

education = tk.Label(root, text="Education",width=20,font=("bold", 10))
education.place(x=40,y=180)

education_entry = tk.Entry(root,width=40,textvariable=education_var)
education_entry.place(x=220,y=180)

address = tk.Label(root, text="Address",width=20,font=("bold", 10))
address.place(x=40,y=260)

address_entry = tk.Entry(root,width=40,textvariable=address_var)
address_entry.place(x=220,y=260)

address1 = tk.Label(root, text="Address 1",width=20,font=("bold", 7))
address1.place(x=240,y=280)

address1_entry = tk.Entry(root,width=40,textvariable=address1_var)
address1_entry.place(x=220,y=300)

Phone = tk.Label(root, text="Phone",width=20,font=("bold", 7))
Phone.place(x=240,y=320)

Phone_entry = tk.Entry(root,width=40,textvariable=phone)
Phone_entry.place(x=220,y=340)


Button(root, text='Submit',width=20,bg='brown',fg='white', command=submit).place(x=220,y=500)

root.mainloop()

FULL NAME =  asfsa
FIRST NAME =  daafagfag
EMAIL =  dvsafdsgew
EDUCATION =  gagd
ADDRESS =  sfefegsh
ADDRESS 1 =  afesgsg
PHONE =  9798833522

FULL NAME =  jayesh
FIRST NAME =  Jayanandan
EMAIL =  jj6144@srmist.edu.in
EDUCATION =  B-tech
ADDRESS =  jharkhand
ADDRESS 1 =  jamshedpur
PHONE =  9798833522